name: Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        default: '20'
      test-command:
        description: 'Command to run tests'
        required: true
        default: 'yarn test'
      use-coravage
       description: 'Use coravage'
       required: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: ${{ inputs.test-command }}
