name: lint

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use (default `20`)
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string

jobs:
  lint:
    name: Linting
    runs-on: ${{ inputs.operating-system }}
    steps:
     - name: Add problem matchers
       run: echo "::add-matcher::.github/problemMatchers/eslint.json"
     - name: Linting
       uses: wolfstar-project/.github/.github/workflows/reusable-yarn-job.yml@main
       with:
            script-name: lint --fix=false
            operating-system: ${{ inputs.operating-system }}
            node-version: ${{ inputs.node-version }}
  