name: Publish Docker Image

on:
  workflow_call:
    inputs:
      registryImage:
        required: false
        type: string
        description: 'The image name to use for the Docker image'
      depotProject:
        required: true
        type: string
        description: 'The Depot project ID to build this image with (see https://depot.dev)'
      platforms:
        required: false
        type: string
        description: 'Comma-separated platforms to build the Docker image for'
        default: 'linux/amd64,linux/arm64'
      tag:
        required: false
        type: string
        default: 'latest'
        description: 'The tag to use for the Docker image'
      context:
        required: false
        type: string
        default: '.'
        description: 'The build context to use for the Docker image'
      dockerFile:
        required: false
        type: string
        default: 'Dockerfile'
        description: 'The Dockerfile to use for the Docker image'
      commitHash:
        required: false
        type: string
        default: ${{ github.sha }}
        description: 'The commit hash to use for the Docker image'
    secrets:
      DEPOT_TOKEN:
        required: true
        description: 'Depot API token used to authenticate the build (see https://depot.dev/docs/cli/authentication)'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.registryImage || github.repository }}

jobs:
  build-and-push:
    name: Build and push (multi-platform via Depot)
    runs-on: depot-ubuntu-24.04-4
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=raw,value=${{ inputs.commitHash || github.sha }}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: ${{ inputs.depotProject }}
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerFile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
