name: Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        type: string
        required: true
        default: '20'
      operating-system:
        description: 'The operating system to use (default `ubuntu-latest`)'
        required: false
        default: ubuntu-latest
        type: string
      enable-test:
        description: 'Enable test runners'
        type: boolean
        default: false
        required: false
      build:
        description: 'Enable build'
        type: boolean
        default: false
        required: false

jobs:
  ci:
    runs-on: ${{ inputs.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Build
        if: ${{ inputs.build }}
        uses: wolfstar-project/.github/.github/workflows/reusable-build.yml@main
        with:
             operating-system: ${{ inputs.operating-system }}
             node-version: ${{ inputs.node-version }}
      - name: Run tests 
        if: ${{ inputs.enable-test }}
        uses: wolfstar-project/.github/.github/workflows/reusable-tests.yml@main
        with:
             operating-system: ${{ inputs.operating-system }}
             node-version: ${{ inputs.node-version }}
